name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: General Stats
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          filename: metrics.general.svg
          base: header, activity, community, repositories
          plugin_lines: yes
          plugin_lines_sections: base
          config_timezone: America/New_York
          config_order: base.header, base.activity+community, base.repositories

      - name: Languages
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          filename: metrics.languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
          config_timezone: America/New_York

      - name: Isometric Calendar
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          filename: metrics.isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: America/New_York

      - name: Coding Habits
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          filename: metrics.habits.svg
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_trim: yes
          config_timezone: America/New_York
          plugins_errors_fatal: no
