name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: readme-update
  cancel-in-progress: false

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: General Stats
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          filename: metrics.general.svg
          base: header, activity, community, repositories
          plugin_lines: yes
          plugin_lines_sections: base
          config_timezone: America/New_York
          config_order: base.header, base.activity+community, base.repositories

      - name: Isometric Calendar
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          filename: metrics.isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: America/New_York
